# Generated by Django 5.2.1 on 2025-06-10 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chai', '0004_alter_chaivariety_price_chaicertificate_chaireview_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chaicertificate',
            old_name='certificate_no',
            new_name='certificate_number',
        ),
    ]
