# Generated by Django 5.2.1 on 2025-06-10 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chai', '0005_rename_certificate_no_chaicertificate_certificate_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chaicertificate',
            old_name='issue_date',
            new_name='issued_date',
        ),
        migrations.RenameField(
            model_name='store',
            old_name='chai_varities',
            new_name='chai_varieties',
        ),
    ]
